### PR TITLE
[GLUTEN-10215][VL] Delta Write: Offload DeltaOptimizedWriterExec

### LINKED ISSUE #11421: OOM due to Hash based shuffle
### Backend

VL (Velox)

### Bug description

When we try to create TPCDS table using deltalake in cluster format, get the error below. Not sure why spill isn't triggered during the OOM.

```
04:15:02  Caused by: org.apache.gluten.exception.GlutenException: org.apache.gluten.exception.GlutenException: Error during calling Java code from native code: org.apache.gluten.memory.memtarget.ThrowOnOomMemoryTarget$OutOfMemoryException: Not enough spark off-heap execution memory. Acquired: 8.0 MiB, granted: 614.4 KiB. Try tweaking config option spark.memory.offHeap.size to get larger space to run this application (if spark.gluten.memory.dynamic.offHeap.sizing.enabled is not enabled). 
04:15:02  Current config settings: 
04:15:02  	spark.memory.offHeap.enabled=True
04:15:02  	spark.gluten.memory.dynamic.offHeap.sizing.enabled=N/A
04:15:02  	spark.gluten.memory.offHeap.size.in.bytes=99.8 GiB
04:15:02  	spark.gluten.memory.task.offHeap.size.in.bytes=6.6 GiB
04:15:02  	spark.gluten.memory.conservative.task.offHeap.size.in.bytes=3.3 GiB
04:15:02  Memory consumer stats: 
04:15:02  	Task.9135:                                                       Current used bytes:    6.6 GiB, peak bytes:        N/A
04:15:02  	+- org.apache.spark.shuffle.sort.ShuffleExternalSorter@41b2766d: Current used bytes:    5.8 GiB, peak bytes:        N/A
04:15:02  	+- Gluten.Tree.3873:                                             Current used bytes:  920.0 MiB, peak bytes: 1344.0 MiB
04:15:02  	|  \- Capacity[8.0 EiB].3873:                                    Current used bytes:  920.0 MiB, peak bytes: 1344.0 MiB
04:15:02  	|     +- NativePlanEvaluator-3680.0:                             Current used bytes:  920.0 MiB, peak bytes: 1344.0 MiB
04:15:02  	|     |  \- single:                                              Current used bytes:  920.0 MiB, peak bytes: 1344.0 MiB
04:15:02  	|     |     +- root:                                             Current used bytes:  920.0 MiB, peak bytes: 1344.0 MiB
04:15:02  	|     |     |  +- task.Gluten_Stage_343_TID_9135_VTID_3680:      Current used bytes:  920.0 MiB, peak bytes: 1344.0 MiB
04:15:02  	|     |     |  |  \- node.0:                                     Current used bytes:  920.0 MiB, peak bytes: 1344.0 MiB
04:15:02  	|     |     |  |     +- op.0.0.0.TableScan:                      Current used bytes:  920.0 MiB, peak bytes: 1342.1 MiB
04:15:02  	|     |     |  |     \- op.0.0.0.TableScan.test-hive:            Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     |     |  \- default_leaf:                                  Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     |     \- gluten::MemoryAllocator:                          Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     |        \- default:                                       Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     +- NativePlanEvaluator-3680.0.OverAcquire.0:               Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     +- IteratorMetrics.2951:                                   Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     |  \- single:                                              Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     |     +- root:                                             Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     |     |  \- default_leaf:                                  Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     |     \- gluten::MemoryAllocator:                          Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     |        \- default:                                       Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	|     \- IteratorMetrics.2951.OverAcquire.0:                     Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	\- Gluten.Tree.3877:                                             Current used bytes: 1024.0 KiB, peak bytes:    8.0 MiB
04:15:02  	   \- Capacity[8.0 EiB].3877:                                    Current used bytes: 1024.0 KiB, peak bytes:    8.0 MiB
04:15:02  	      +- VeloxColumnarToRow.2215:                                Current used bytes: 1024.0 KiB, peak bytes:    8.0 MiB
04:15:02  	      |  \- single:                                              Current used bytes: 1024.0 KiB, peak bytes:    8.0 MiB
04:15:02  	      |     +- root:                                             Current used bytes: 1024.0 KiB, peak bytes: 1024.0 KiB
04:15:02  	      |     |  \- default_leaf:                                  Current used bytes: 1024.0 KiB, peak bytes: 1024.0 KiB
04:15:02  	      |     \- gluten::MemoryAllocator:                          Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	      |        \- default:                                       Current used bytes:      0.0 B, peak bytes:      0.0 B
04:15:02  	      \- VeloxColumnarToRow.2215.OverAcquire.0:                  Current used bytes:      0.0 B, peak bytes:      0.0 B
```

### Gluten version

_No response_

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

```bash

```

### PR DESCRIPTION
**Pull request by zhztheplayer**
The PR aims to offload the Spark shuffle generated during executing Delta write command with write optimization enabled, to fix https://github.com/apache/incubator-gluten/issues/11421.

The PR is tested by the test code added in https://github.com/apache/incubator-gluten/pull/11430.

The PR is WIP.

Related issue: #10215

### CODE REVIEW

**Comment by zhztheplayer** [comment]
PR status:

When running the test case: https://github.com/apache/incubator-gluten/blob/4cd6440d23665d8807fbf1fc0d470a148accf020/backends-velox/src-delta33/test/scala/org/apache/spark/sql/delta/perf/OptimizedWritesSuite.scala#L124-L134, an error "Stream is corrupted" from the shuffle reader is raised:

```
E20260121 18:29:26.731045 420393 Exceptions.h:53] Line: /opt/code/incubator-gluten/ep/build-velox/build/velox_ep/velox/exec/Driver.cpp:582, Function:operator(), Expression:  Operator::getOutput failed for [operator: ValueStream, plan node ID: 0]: Error during calling Java code from native code: org.apache.gluten.exception.GlutenException: org.apache.gluten.exception.GlutenException: Error during calling Java code from native code: org.apache.spark.shuffle.FetchFailedException: Block shuffle_0_0_1805 is corrupted but the cause is unknown
	at org.apache.spark.errors.SparkCoreErrors$.fetchFailedError(SparkCoreErrors.scala:437)
	at org.apache.spark.storage.ShuffleBlockFetcherIterator.throwFetchFailedException(ShuffleBlockFetcherIterator.scala:1239)
	at org.apache.spark.storage.BufferReleasingInputStream.tryOrFetchFailedException(ShuffleBlockFetcherIterator.scala:1398)
	at org.apache.spark.storage.BufferReleasingInputStream.read(ShuffleBlockFetcherIterator.scala:1374)
	at org.apache.gluten.vectorized.OnHeapJniByteInputStream.read(OnHeapJniByteInputStream.java:39)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeNext(Native Method)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.next0(ColumnarBatchOutIterator.java:63)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.next0(ColumnarBatchOutIterator.java:28)
	at org.apache.gluten.iterator.ClosableIterator.next(ClosableIterator.java:48)
	at org.apache.gluten.vectorized.ColumnarBatchSerializerInstanceImpl$TaskDeserializationStream.liftedTree1$1(ColumnarBatchSerializer.scala:188)
	at org.apache.gluten.vectorized.ColumnarBatchSerializerInstanceImpl$TaskDeserializationStream.readValue(ColumnarBatchSerializer.scala:187)
	at org.apache.spark.serializer.DeserializationStream$$anon$2.getNext(Serializer.scala:188)
	at org.apache.spark.serializer.DeserializationStream$$anon$2.getNext(Serializer.scala:185)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:32)
	at org.apache.gluten.vectorized.ColumnarBatchInIterator.hasNext(ColumnarBatchInIterator.java:36)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
	at org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNext0(ColumnarBatchOutIterator.java:58)
	at org.apache.gluten.iterator.ClosableIterator.hasNext(ClosableIterator.java:36)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:45)
	at org.apache.gluten.iterator.IteratorsV1$InvocationFlowProtection.hasNext(IteratorsV1.scala:154)
	at org.apache.gluten.iterator.IteratorsV1$IteratorCompleter.hasNext(IteratorsV1.scala:66)
	at org.apache.gluten.iterator.IteratorsV1$PayloadCloser.hasNext(IteratorsV1.scala:38)
	at org.apache.gluten.iterator.IteratorsV1$LifeTimeAccumulator.hasNext(IteratorsV1.scala:95)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at org.apache.spark.sql.delta.files.GlutenDeltaFileFormatWriter$.executeTask(GlutenDeltaFileFormatWriter.scala:452)
	at org.apache.spark.sql.delta.files.GlutenDeltaFileFormatWriter$.$anonfun$executeWrite$4(GlutenDeltaFileFormatWriter.scala:311)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Stream is corrupted
	at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:202)
	at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:159)
	at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:172)
	at org.apache.spark.storage.BufferReleasingInputStream.$anonfun$read$2(ShuffleBlockFetcherIterator.scala:1374)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at org.apache.spark.storage.BufferReleasingInputStream.tryOrFetchFailedException(ShuffleBlockFetcherIterator.scala:1389)
	... 37 more
```

File: backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala [hunk 1]
```diff
@@ -0,0 +1,352 @@
...
+import scala.concurrent.duration.Duration
+
+/** Gluten's vectorized version of [[DeltaOptimizedWriterExec]]. */
+case class GlutenDeltaOptimizedWriterExec(
+    child: SparkPlan,
+    partitionColumns: Seq[String],
+    @transient deltaLog: DeltaLog
+) extends ValidatablePlan
+  with UnaryExecNode
+  with DeltaLogging {
```
Comment (zhztheplayer) [inline backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala:60]: This class is modified from the Delta 3.3 class: https://github.com/delta-io/delta/blob/v3.3.0/spark/src/main/scala/org/apache/spark/sql/delta/perf/DeltaOptimizedWriterExec.scala.

We mainly need to offload the row-based shuffle as an `columnarShufflePlan` which is placed as a member field of this new class.

**Comment by marin-ma** [comment]
Is it that the shuffle writer uses native shuffle write, but the reader is trying to decompress on the java side?

```
Caused by: java.io.IOException: Stream is corrupted
	at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:202)
	at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:159)
	at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:172)
	at org.apache.spark.storage.BufferReleasingInputStream.$anonfun$read$2(ShuffleBlockFetcherIterator.scala:1374)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at org.apache.spark.storage.BufferReleasingInputStream.tryOrFetchFailedException(ShuffleBlockFetcherIterator.scala:1389)
	... 37 more
```

File: backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala [hunk 2]
```diff
@@ -0,0 +1,352 @@
...
+  }
+
+  override def clearDependencies(): Unit = {
+    super.clearDependencies()
+    dep = null
+  }
+}
+
+/** A simplified implementation of the `BlockStoreShuffleReader` for reading shuffle blocks. */
+private class GlutenOptimizedWriterShuffleReader(
```
Comment (marin-ma) [inline backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala:305]: Seems like this simplified shuffle reader implementation is quite similar to `ColumnarShuffleReader`. Can we just use `ColumnarShuffleReader` here?

File: backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala [hunk 3]
```diff
@@ -0,0 +1,352 @@
...
+
+  /** Read the combined key-values for this reduce task */
+  override def read(): Iterator[Product2[Int, ColumnarBatch]] = {
+    val wrappedStreams = new ShuffleBlockFetcherIterator(
+      context,
+      SparkEnv.get.blockManager.blockStoreClient,
+      SparkEnv.get.blockManager,
+      SparkEnv.get.mapOutputTracker,
+      blocks,
+      SparkEnv.get.serializerManager.wrapStream,
```
Comment (marin-ma) [inline backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala]: Should use ` ColumnarShuffleManager.bypassDecompressionSerializerManger` for ColumnarShuffleDependency

**Comment by FelixYBW** [comment]
Cluster format still have fallback shuffle

SQL:
```
        spark.sql(f''' CREATE TABLE {databasename}.{tbl}
                    USING DELTA
                    TBLPROPERTIES (
                      delta.autoOptimize.autoCompact = true,
                      delta.autoOptimize.optimizeWrite = true,
                      delta.dataSkippingNumIndexedCols = 128
                    )
                    CLUSTER BY ({partcol})
                    LOCATION 's3a://presto-workload/{databasename}/{tbl}'
                    AS SELECT *
                    FROM tpcds_sf2500_parquet_zstd_135_nonpart.{tbl}''')
```

image

File: backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala (hunk 2 above)
Comment (zhztheplayer) [reply backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala:305]: > Seems like this simplified shuffle reader implementation is quite similar to ColumnarShuffleReader.

I was following Delta's practice to add a new inner reader class here. I thought it was the safest move in the first iteration.

> Can we just use ColumnarShuffleReader here?

Yes, we can give it a try later on.

File: backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala (hunk 3 above)
Comment (zhztheplayer) [reply backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala]: Thanks for the suggestion. The issue has been fixed.

**Comment by zhztheplayer** [comment]
> Cluster format still have fallback shuffle
> 
> SQL:
> 
> ```
>         spark.sql(f''' CREATE TABLE {databasename}.{tbl}
>                     USING DELTA
>                     TBLPROPERTIES (
>                       delta.autoOptimize.autoCompact = true,
>                       delta.autoOptimize.optimizeWrite = true,
>                       delta.dataSkippingNumIndexedCols = 128
>                     )
>                     CLUSTER BY ({partcol})
>                     LOCATION 's3a://presto-workload/{databasename}/{tbl}'
>                     AS SELECT *
>                     FROM tpcds_sf2500_parquet_zstd_135_nonpart.{tbl}''')
> ```
> 
> image

If I repeated it correctly, this should be fixed in https://github.com/apache/incubator-gluten/pull/11461/commits/7f1fe98e38bdc876eb008433562a094ed012f0a6.

File: backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala [hunk 4]
```diff
@@ -370,7 +370,15 @@ class VeloxSparkPlanExecApi extends SparkPlanExecApi {
...
-        val hashExpr = new Murmur3Hash(exprs)
+        val hashExpr = if (exprs.isEmpty) {
+          // In Spark, a hash expression with empty input is not resolvable and an
+          // `WRONG_NUM_ARGS.WITHOUT_SUGGESTION` error will be reported when validating the project
+          // transformer. So we directly return the seed here, which is the intended hashed value
+          // for empty input given Spark's murmur3 hash logic.
+          Literal(new Murmur3Hash(Nil).seed, IntegerType)
+        } else {
+          new Murmur3Hash(exprs)
+        }
```
Comment (zhztheplayer) [inline backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala:381]: cc @marin-ma Let me know if any thoughts about this change.

Comment (marin-ma) [reply backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxSparkPlanExecApi.scala:381]: Looks good. Thanks!

**Comment by FelixYBW** [comment]
@zhli1142015 Have you solved this in your case?

**Comment by FelixYBW** [comment]
> If I repeated it correctly, this should be fixed in [7f1fe98](https://github.com/apache/incubator-gluten/commit/7f1fe98e38bdc876eb008433562a094ed012f0a6).

~confirm solved~

There is still a C2R/R2C after exchange
image

project fallback is caused by this expression:

`cast(interleavebits(partitionerexpr(ss_sold_date_sk#21912, org.apache.spark.RangePartitioner@65a83683)) as string) AS 839937ac-4cf5-4d34-ad8e-bdfc956670f9-rpKey1#22027`

**Review by FelixYBW — APPROVED** [review]

**Comment by zhztheplayer** [comment]
> There is still a C2R/R2C after exchange

Yes, it was expected and I've marked the reason [here](https://github.com/apache/incubator-gluten/pull/11461/files#diff-44537c8d54133707205e1318508c50245a2956642d5b96d14d03b5ee5f09b10fR111-R113). Will follow up later.

File: backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala [hunk 5]
```diff
@@ -0,0 +1,365 @@
...
+    try {
+      val res = getStats()
+      if (res.isEmpty) awaitShuffleMapStage()
+      getStats()
+    } catch {
+      case e: FetchFailedException =>
+        logWarning(log"Failed to fetch shuffle blocks for the optimized writer. Retrying", e)
+        awaitShuffleMapStage()
+        getStats()
+        throw e
```
Comment (felipepessoto) [inline backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala:185]: @zhztheplayer is this `throw e` expected? It seems we have a retry, but after it, we rethrow the exception

Comment (zhztheplayer) [reply backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala:185]: Thanks, and yes, this looks a bit off, could be unexpectedly brought to the PR from some test code.

Comment (felipepessoto) [reply backends-velox/src-delta33/main/scala/org/apache/spark/sql/delta/perf/GlutenDeltaOptimizedWriterExec.scala:185]: https://github.com/apache/gluten/pull/11978

**Comment by felipepessoto** [comment]
@zhztheplayer I cant find the GlutenDeltaOptimizedWriterExec class in the JAR downloaded from https://www.apache.org/dyn/closer.lua/gluten/1.6.0/apache-gluten-1.6.0-bin-spark-4.0.tar.gz. Do you know what I'm doing wrong?

Thanks

**Comment by zhztheplayer** [comment]
@felipepessoto the 1.6 release excludes all lake format supports for 4.0 (see note `RSS / Lake = OFF`): https://github.com/apache/gluten/releases/tag/v1.6.0.

**Comment by felipepessoto** [comment]
@zhztheplayer the https://github.com/apache/gluten/blob/main/.github/workflows/velox_backend_x86.yml has the `-Pdelta` flag. Is the `Lake = OFF` set by another flag?

Do you have any PR/issue/doc where I can find more info about it?
At least for previous versions I wasn't aware of this `Lake` flag, is it new?

**Comment by zhztheplayer** [comment]
@felipepessoto please refer to the build script used: https://github.com/apache/gluten/blob/v1.6.0/dev/release/build-release.sh, the build command may be different from GHA CI.

**Comment by zhztheplayer** [comment]
@felipepessoto the build process is also documented at https://github.com/apache/gluten/blob/main/docs/developers/HowToRelease.md
